### ISSUE TITLE
two error occurred when I try to build this project on my mac 

### ISSUE THREAD

**Issue by ffr** [smistad/Tube-Segmentation-Framework#3]
OS X 10.11.6
git clone --recurse-submodules https://github.com/smistad/Tube-Segmentation-Framework.git
cd Tube-Segmentation-Framework
cmake .
make -j8
Then I got this:

In file included from /Users/Leon/Developer/Tube-Segmentation-Framework/SIPL/Core.cpp:6:
/Users/Leon/Developer/Tube-Segmentation-Framework/SIPL/Core.hpp:762:15: error: 
      no matching constructor for initialization of 'SIPL::ConversionException'
  ...ConversionException("image size mismatch in assignment", **LINE**, **FILE**);
     ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/Leon/Developer/Tube-Segmentation-Framework/SIPL/Exceptions.hpp:164:7: note: 
      candidate constructor (the implicit copy constructor) not viable: requires
      1 argument, but 3 were provided
class ConversionException : public SIPLException {
      ^
/Users/Leon/Developer/Tube-Segmentation-Framework/SIPL/Exceptions.hpp:164:7: note: 
      candidate constructor (the implicit move constructor) not viable: requires
      1 argument, but 3 were provided
/Users/Leon/Developer/Tube-Segmentation-Framework/SIPL/Exceptions.hpp:164:7: note: 
      candidate constructor (the implicit default constructor) not viable:
      requires 0 arguments, but 3 were provided
In file included from /Users/Leon/Developer/Tube-Segmentation-Framework/SIPL/Core.cpp:6:
/Users/Leon/Developer/Tube-Segmentation-Framework/SIPL/Core.hpp:802:15: error: 
      no matching constructor for initialization of 'SIPL::ConversionException'
  ...ConversionException("volume size mismatch in assignment", **LINE**, **FILE**);
     ^                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by smistad** [comment]
It seems ConversionException is missing some constructors, you can copy them from SIPLException. Unsure why this compiles fine on linux..

**Comment by rahulpk** [comment]
Hi,
On my mac, once I solved the above issue as you suggested, new errors have popped-up.
/Coding/Source/Erik-Tube-Segmentation/tube-segmentation.cpp:1208:23: error: use of overloaded operator '+' is ambiguous (with operand types 'SIPL::int3' and 'SIPL::float3')
                                float3 n = a->pos + frac_direction;
                                           ~~~~~~ ^ ~~~~~~~~~~~~~~
/Coding/Source/Erik-Tube-Segmentation/SIPL/Types.hpp:373:8: note: candidate function [with T = SIPL::int3]
float3 operator+(T scalar, float3 other) {
       ^
/Coding/Source/Erik-Tube-Segmentation/SIPL/Types.hpp:445:12: note: candidate function [with T = SIPL::float3]
int3 int3::operator+(float3 other) const {
           ^
/Coding/Source/Erik-Tube-Segmentation/tube-segmentation.cpp:1227:23: error: use of overloaded operator '+' is ambiguous (with operand types 'SIPL::int3' and 'SIPL::float3')
                                float3 n = a->pos + frac_direction;
                                           ~~~~~~ ^ ~~~~~~~~~~~~~~
/Coding/Source/Erik-Tube-Segmentation/SIPL/Types.hpp:373:8: note: candidate function [with T = SIPL::int3]
float3 operator+(T scalar, float3 other) {
       ^
/Coding/Source/Erik-Tube-Segmentation/SIPL/Types.hpp:445:12: note: candidate function [with T = SIPL::float3]
int3 int3::operator+(float3 other) const {
           ^

**Comment by smistad** [comment]
I don't have a Mac available atm, so I am unable to fix this. Still, this code never worked that well on Mac due to the use of OpenCL which unfortunately doesn't work properly on Mac.

**Comment by rahulpk** [comment]
thats unfortunate. Would have get my hands on linux then.

**Comment by smistad** [comment]
Yes, it is annoying that Apple, the founders of OpenCL, can't make proper OpenCL drivers. Also, note that this code has been moved to [FAST](http://github.com/smistad/FAST), a framework with similar semantics as VTK/ITK.

**Comment by rahulpk** [comment]
I will try with FAST. Thanks!

**Comment by xiaocccccc** [comment]
Hi,I'm the new..I would like to know will this code work well on Windows??

**Comment by smistad** [comment]
It has been a while since I tested this code on Windows. In theory it is possible, but there might be some minor issues.

**Comment by xiaocccccc** [comment]
thx,I，l‘ll try it.
