### ISSUE TITLE
Error occurred when compiling

### ISSUE THREAD

**Issue by ChenglongWang** [smistad/Tube-Segmentation-Framework#4]
Hello

When I compile this project. Error was occurred: 

> error C2664: 'oul::HistogramPyramid3DBuffer::HistogramPyramid3DBuffer(const oul::HistogramPyramid3DBuffer &)' : cannot convert argument 1 from 'OpenCL' to 'oul::Context &'

Source code is :  oul::HistogramPyramid3D hp3(ocl);

That means, there is no conversion between oul::Context and OpenCL. I'm using the newest version OpenCLUtilityLibrary (master) and Tube-Segmentation-Framework (master). I'm wondering if I have a mismatched version.

Thank you very much.

**Comment by smistad** [comment]
Most likely you have the wrong version. You should have the one that corresponds to git SHA 73de6709a7e722ffba0523258418bf364c31c43a [https://github.com/smistad/OpenCLUtilityLibrary/tree/73de6709a7e722ffba0523258418bf364c31c43a](https://github.com/smistad/OpenCLUtilityLibrary/tree/73de6709a7e722ffba0523258418bf364c31c43a)

You can also fetch the correct version with git:
```bash
<in your checked out tube-segmentation-framework directory>
git submodule init
git submodule update
```

**Comment by ChenglongWang** [comment]
Thank you very much. This version solved the problem.
